CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido_p VARCHAR2(100) NOT NULL,
    apellido_m VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100) NOT NULL UNIQUE,
    telefono VARCHAR2(15) NOT NULL,
    contrasella VARCHAR2(100) NOT NULL
);

SELECT * FROM usuarios;

CREATE TABLE perros (
    --crear un id desde 100, 101, 102, ...
    --si no se especifica el id, se incrementa automaticamente
    --si se especifica el id, se usa ese id
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    raza VARCHAR2(100) NOT NULL,
    edad NUMBER NOT NULL,
    peso NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

SELECT * FROM perros;

CREATE TABLE pagos(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY (start with 001) PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    fecha DATE NOT NULL,
    monto NUMBER NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
)


